- name: Install the Maven on EC2
  hosts: localhost
  become: true
  tasks:
  - name: Download Java
    get_url:
      #url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
      url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
      dest: /opt/jdk-8u60-linux-x64.rpm
      #headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
      headers: "Cookie: oraclelicense=accept-securebackup-cookie" 
  - name: Install Java
    yum:
      name: /opt/jdk-8u60-linux-x64.rpm
      state: present
  - name: Download the Maven installation/zip file
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      dest: /opt/apache-maven-3.8.6-bin.tar.gz
        #- name: Maven Installation
        #yum:
        #name: maven
        #state: present
  - name: Unzip the file 
    ansible.builtin.unarchive:
      src: /opt/apache-maven-3.8.6-bin.tar.gz
      dest: /opt
  - name: Make the Symbolic like for mvn
    ansible.builtin.file:
      src: /opt/apache-maven-3.8.6/bin/mvn
      dest: /usr/bin/mvn
      state: link
  - name: Update the Profile file 
    lineinfile:
      path: /etc/profile
      state: present
      line: "{{ item }}"
    with_items:
      - 'export M2_HOME="/opt/apache-maven-3.8.6"'
      - 'export PATH=$PATH:$M2_HOME/bin' 
  - name: Source the Profile file
    shell:
      cmd: source /etc/profile
